In [8]:
import torch
import numpy as np

a rank zero tensor is a scalar, \
by default its **float**


In [3]:
# PyTorch
a = torch.tensor(1.)
print(a)
print(a.shape)

tensor(1.)
torch.Size([])


rank 1 tensor = vector

In [4]:
a = torch.tensor([1., 2., 3.])
print(a)
print(a.shape)

tensor([1., 2., 3.])
torch.Size([3])


rank 2 tensor = matrix

In [5]:
a = torch.tensor([
  [1., 2., 3.],
  [2., 3., 4.]
])

print(a.shape)
print(a.ndim)#dim=num of rows
print(a.dtype)

torch.Size([2, 3])
2
torch.float32



### **3D Tensor**
An RGB image. It is a stack of matrices\
3D tensor, one matrix on top of another

In [6]:
a = torch.tensor([
  [
    [1., 2., 3.],
    [2., 3., 4.]
  ],
  [
    [5., 6., 7.],
    [8., 9., 10.]
  ]
])
print(a.shape)

torch.Size([2, 2, 3])



We can think of PyTorch tensors as NumPy arrays with some additional functionality, such as automatic differentiation and computations on a GPU

In [9]:
#to convert from numpy
np_array = np.array([1., 2., 3.])
a = torch.from_numpy(np_array)
print(a)
# OR
a = torch.tensor(np_array)
print(a)

tensor([1., 2., 3.], dtype=torch.float64)
tensor([1., 2., 3.], dtype=torch.float64)


In [10]:
# to change datatyoe
print(a.dtype)
a = a.to(torch.float32)
print(a.dtype)

torch.float64
torch.float32


In [13]:
#give this tensor:
a = torch.tensor([
  [1., 2., 3.],
  [2., 3., 4.]
])
print(a)
#to change shape you can use this
print(a.view(3, 2))

tensor([[1., 2., 3.],
        [2., 3., 4.]])
tensor([[1., 2.],
        [3., 2.],
        [3., 4.]])


In [14]:
#to transpose
a.T

tensor([[1., 2.],
        [2., 3.],
        [3., 4.]])